### ISSUE TITLE
Falha na autenticação de usuários via github

### ISSUE THREAD

**Issue by Gschwend** [linea-it/pz-server#74]
ShibbolethValidationError at /api/shib/

All required Shibboleth elements not found.  {'username': 'AndressaWille'}

Request Method: 	GET
Request URL: 	https://pz-server-dev.linea.org.br/api/shib/?next=/
Django Version: 	4.0.2
Exception Type: 	ShibbolethValidationError
Exception Value: 	

All required Shibboleth elements not found.  {'username': 'AndressaWille'}

Exception Location: 	/opt/venv/lib/python3.10/site-packages/shibboleth/middleware.py, line 50, in process_request
Python Executable: 	/opt/venv/bin/uwsgi
Python Version: 	3.10.8
Python Path: 	

['.',
 '',
 '/usr/local/lib/python310.zip',
 '/usr/local/lib/python3.10',
 '/usr/local/lib/python3.10/lib-dynload',
 '/opt/venv/lib/python3.10/site-packages']

Server time: 	Mon, 07 Nov 2022 14:36:13 +0000

**Comment by Gschwend** [comment]
All required Shibboleth elements not found.  {'username': 'gabrieloliveira2428', 'first_name': 'Gabriel Oliveira', 'last_name': 'Gabriel Oliveira'}
Request Method:GETRequest URL:https://pz-server-dev.linea.org.br/api/shib/?next=/Django Version:4.0.2Exception Type:ShibbolethValidationErrorException Value:All required Shibboleth elements not found.  {'username': 'gabrieloliveira2428', 'first_name': 'Gabriel Oliveira', 'last_name': 'Gabriel Oliveira'}
Exception Location:/opt/venv/lib/python3.10/site-packages/shibboleth/middleware.py, line 50, in process_requestPython Executable:/opt/venv/bin/uwsgiPython Version:3.10.8Python Path:['.',
 '',
 '/usr/local/lib/python310.zip',
 '/usr/local/lib/python3.10',
 '/usr/local/lib/python3.10/lib-dynload',
 '/opt/venv/lib/python3.10/site-packages']
Server time:Mon, 07 Nov 2022 14:51:31 +0000
[11:54](https://lineateam.slack.com/archives/D02N9G12KGX/p1667832866326609)
Environment:
Request Method: GET
Request URL: https://pz-server-dev.linea.org.br/api/shib/?next=/
Django Version: 4.0.2
Python Version: 3.10.8
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'corsheaders',
 'django_filters',
 'rest_framework',
 'drf_spectacular',
 'rest_framework.authtoken',
 'oauth2_provider',
 'social_django',
 'drf_social_oauth2',
 'shibboleth',
 'core']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'core.shibboleth.ShibbolethMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 125, in __call__
    response = self.process_request(request)
  File "/opt/venv/lib/python3.10/site-packages/shibboleth/middleware.py", line 50, in process_request
    raise ShibbolethValidationError("All required Shibboleth elements"
Exception Type: ShibbolethValidationError at /api/shib/
Exception Value: All required Shibboleth elements not found.  {'username': 'gabrieloliveira2428', 'first_name': 'Gabriel Oliveira', 'last_name': 'Gabriel Oliveira'}

**Comment by Gschwend** [comment]
https://github.com/linea-it/pz-server/pull/75
